# Filters used by [dorny/path-filters](https://github.com/dorny/paths-filter)
# to detect changes in each subproject, and only run the corresponding jobs.

encoder: &encoder
  - "Cargo.toml"
  - "Cargo.lock"
  - "rust/**"

extensions: &extensions
  - "Cargo.toml"
  - "Cargo.lock"
  - "extensions/**"

extensions_data: &extensions_data
  - "src/guppyft/extensions/data/**"

rust:
  - *encoder
  - *extensions
  - *extensions_data

python:
  - *encoder
  - "pyproject.toml"
  - "uv.lock"
  - "src/guppyft/**"
