[workspace]
resolver = "2"
members = [
    "rust",
    "rust-bindings",
]

[workspace.dependencies]
tket = "0.18.0"
hugr = "0.27.0"
hugr-core = "0.27.0"
itertools = "0.14.0"
derive_more = { version = "2", features = ["display", "from"] }

[profile.dev-py]
inherits = "dev"

[profile.release-py]
inherits = "release"
lto = "fat"
strip = "symbols"
panic = "abort"
