[workspace]
resolver = "2"
members = [
    "rust",
    "rust-bindings",
    "extensions",
]

[workspace.package]
rust-version = "1.91"
edition = "2024"

[workspace.dependencies]
tket = "0.21.2"
hugr = "0.29.3"
hugr-core = "0.29.3"
itertools = "0.15.0"
derive_more = { version = "2", features = ["display", "from"] }

[patch.crates-io]
hugr = { git = "https://github.com/quantinuum/hugr", rev = "04272109903145df5901bb132ea9ca9c831446fb" }
hugr-core = { git = "https://github.com/quantinuum/hugr", rev = "04272109903145df5901bb132ea9ca9c831446fb" }
hugr-cli = { git = "https://github.com/quantinuum/hugr", rev = "04272109903145df5901bb132ea9ca9c831446fb" }
hugr-model = { git = "https://github.com/quantinuum/hugr", rev = "04272109903145df5901bb132ea9ca9c831446fb" }
tket = { git = "https://github.com/quantinuum/tket2", rev = "13dda8feee30ea43c850e347fcaf405002cb4436" }

[profile.dev-py]
inherits = "dev"

[profile.release-py]
inherits = "release"
lto = "fat"
strip = "symbols"
panic = "abort"
