[workspace]
resolver = "2"
members = [
    "rust",
    "rust-bindings",
    "extensions",
]

[workspace.package]
rust-version = "1.91"
edition = "2024"

[workspace.dependencies]
tket = "0.21.2"
hugr = "0.29.3"
hugr-core = "0.29.3"
itertools = "0.15.0"
derive_more = { version = "2", features = ["display", "from"] }

[patch.crates-io]
hugr = { git = "https://github.com/quantinuum/hugr", rev = "601ee49d41b0e388e6d0dd7a52ce99e1b144e5ef" }
hugr-core = { git = "https://github.com/quantinuum/hugr", rev = "601ee49d41b0e388e6d0dd7a52ce99e1b144e5ef" }
hugr-cli = { git = "https://github.com/quantinuum/hugr", rev = "601ee49d41b0e388e6d0dd7a52ce99e1b144e5ef" }
hugr-model = { git = "https://github.com/quantinuum/hugr", rev = "601ee49d41b0e388e6d0dd7a52ce99e1b144e5ef" }
tket = { git = "https://github.com/quantinuum/tket2", rev = "b0325d3146f20c46722d993fc91dcb1705c871eb" }

[profile.dev-py]
inherits = "dev"

[profile.release-py]
inherits = "release"
lto = "fat"
strip = "symbols"
panic = "abort"
