[project]
name = "guppy-ft"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "guppylang>=0.21.11",
    "guppylang-internals>=0.32.0",
    "hugr>=0.16.0",
    "tket>=0.13.0",
    "guppy-ft-encoder",
]
classifiers = [
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]

[dependency-groups]
dev = [
    "maturin>=1.7.0,<2",
    { include-group = "lint" },
    { include-group = "test" },
]
lint = [
    "ruff>=0.15.11",
]
test = [
    "pytest>=9.0.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/guppyft"]

[tool.uv.sources]
guppy-ft-encoder = { workspace = true }
tket = { git = "https://github.com/quantinuum/tket2", branch = "mr/feat/globals-extension", subdirectory = "tket-py" }
guppylang = { git = "https://github.com/quantinuum/guppylang", branch = "main", subdirectory = "guppylang" }
guppylang-internals = { git = "https://github.com/quantinuum/guppylang", branch = "main", subdirectory = "guppylang-internals" }

[tool.uv.workspace]
members = [
    "encoder",
]

[tool.maturin]
# Maturin is not the build system for the workspace (it is only used for `encoder`).
# We mirror the `encoder/pyproject.toml` config here so `maturin develop` still works
# from the root of the workspace.
module-name = "guppy_ft_encoder._bindings"
python-source = "encoder/src/"
manifest-path = "encoder/Cargo.toml"
features = ["pyo3/extension-module"] # skips linking against libpython.so
profile = "release-py" # See Cargo.toml
