[project]
name = "guppy-ft"
version = "0.1.0"
description = "Tools for fault-tolerant quantum computing in the Guppy language"
requires-python = ">=3.13,<4"
license = { file = "LICENCE" }
authors = [
    { name = "TKET development team", email = "tket-support@quantinuum.com" },
]
maintainers = [
    { name = "TKET development team", email = "tket-support@quantinuum.com" },
]
classifiers = [
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]

dependencies = [
    "guppylang>=0.21.13",
    "guppylang-internals>=0.34.0",
    "hugr>=0.16.0",
    "tket>=0.13.0",
]

[dependency-groups]
dev = [
    "maturin>=1.7.0,<2",
    { include-group = "lint" },
    { include-group = "test" },
]
lint = [
    "pre-commit>=3.6.0,<5",
    "ruff>=0.15.11",
    "ty>=0.0.33",
]
test = [
    "pytest>=9.0.3",
    "selene-hugr-qis-compiler>=0.2.10",
    "selene-sim>=0.2.13",
]

[tool.mypy]
strict = true
allow_redefinition = true

[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[tool.uv.sources]
# Pinned to #1695 while waiting for release
guppylang = { git = "https://github.com/quantinuum/guppylang", rev = "561882f760d48be0327d8785b7b82085ea657957", subdirectory = "guppylang" }
guppylang-internals = { git = "https://github.com/quantinuum/guppylang", rev = "561882f760d48be0327d8785b7b82085ea657957", subdirectory = "guppylang-internals" }
# Needs tket branch for globals extension
tket = { git = "https://github.com/quantinuum/tket2", rev = "8ee327069011ac5bfb9d8b175f9aa196195834e2", subdirectory = "tket-py" }
selene-hugr-qis-compiler = { git = "https://github.com/quantinuum/tket2", rev = "8ee327069011ac5bfb9d8b175f9aa196195834e2", subdirectory = "qis-compiler" }

[tool.maturin]
module-name = "guppyft._bindings"
python-source = "src/"
manifest-path = "encoder-bindings/Cargo.toml"
features = ["pyo3/extension-module"] # skips linking against libpython.so
profile = "dev-py" # See root Cargo.toml
