[package]
name = "guppy-ft"
description = "Guppy FT Rust utilities and modules"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
publish = false

[lints.rust]
missing_docs = "warn"

[dependencies]
tket = { workspace = true }
hugr = { workspace = true }
hugr-core = { workspace = true }
itertools = { workspace = true }
derive_more = { workspace = true }
