[package]
name = "guppy-ft"
description = "Guppy FT Rust utilities and modules"
version = "0.1.0"
edition = "2024"
publish = false
rust-version = "1.91.0"

[lints.rust]
missing_docs = "warn"

[dependencies]
tket = { workspace = true }
hugr = { workspace = true }
hugr-core = { workspace = true }
itertools = { workspace = true }
derive_more = { workspace = true }
