name: All Rust and Python tests

on:
  schedule:
    # Nightly at 4am
    - cron: "0 4 * * *"
  pull_request:
    types: [labeled]
  workflow_dispatch: { }

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  UV_VERSION: "0.11.7"

jobs:
  # Run tests on Rust stable
  check-rs:
    if: github.event_name == "schedule" || github.event_name == "workflow_dispatch"
    name: 🦀 Test Rust code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: mozilla-actions/sccache-action@v0.0.11
      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "stable"
      - name: Configure default rust toolchain
        run: rustup override set ${{steps.toolchain.outputs.name}}
      - uses: taiki-e/install-action@nextest
      - name: Test with all features
        run: cargo nextest r --verbose --workspace

  check-py:
    if: github.event_name == "schedule" || github.event_name == "workflow_dispatch" || github.event.label.name == "X-nightly-ci"
    name: 🐍 Test Python code
    runs-on: ubuntu-latest
    env:
      LLVM_SYS_211_PREFIX: /usr/lib/llvm-21
    steps:
      - uses: actions/checkout@v7
      - uses: mozilla-actions/sccache-action@v0.0.11
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true
      - name: Install dependencies
        run: uv sync --frozen --python 3.14
      - name: Run tests
        run: uv run pytest -n auto
