name: Build wheels

on:
  push:
    branches:
      - main
      - "release-please--*"
      - "mr/chore/publish-wheels-to-pipy"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build_wheels:
    name: ${{ matrix.os }} wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-15-intel runners are x86_64
        os: [ ubuntu-latest, ubuntu-22.04-arm, macos-latest, macos-15-intel, windows-latest ]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
      - uses: actions/cache@v6
        if: runner.os != 'Linux'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build guppyft wheel
        uses: pypa/cibuildwheel@v4.2.1
        with:
          output-dir: 'wheelhouse'

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*guppyft*.whl

  release:
    name: Release wheels
    runs-on: ubuntu-latest
    if: (github.event_name == 'release' || github.event_name == 'workflow_dispatch') && github.ref_type == 'tag'
    needs: [ build_wheels ]
    permissions:
      contents: write
      id-token: write # mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: wheelhouse
          merge-multiple: true

      - name: Update GitHub release with artifacts
        uses: softprops/action-gh-release@v3
        with:
          files: wheelhouse/*guppyft*.whl

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Publish package distributions to PyPI
        # This workflow is a trusted publisher for the packages on PyPI.
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse
          verbose: true
          skip-existing: true