name: Check Conventional Commits format
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
  merge_group:
    types: [ checks_requested ]

permissions:
  contents: read
  pull-requests: write

jobs:
  check-title:
    name: Check Title
    uses: quantinuum/hugrverse-actions/.github/workflows/pr-title.yml@main
    secrets:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
