name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  merge_group:
    types: [ checks_requested ]
  workflow_dispatch: { }

# Limits the number of concurrent runs of this workflow for branches to one. For non-main branches, runs caused by newly
# pushed commits thus cancel any in-progress runs for the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  UV_VERSION: "0.11.7"

jobs:
  # Check if changes were made to the relevant files.
  # Always returns true if running on the default branch, to ensure all changes are thoroughly checked.
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
      python: ${{ steps.filter.outputs.python }}
      extensions: ${{ steps.filter.outputs.extensions }}
      qis: ${{ steps.filter.outputs.qis }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/check-changes
        id: filter

  # Run tests on Rust stable
  check-rs:
    name: Test Rust code 🦀
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: mozilla-actions/sccache-action@v0.0.10
      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "stable"
      - name: Configure default rust toolchain
        run: rustup override set ${{steps.toolchain.outputs.name}}
      - uses: quantinuum/hugrverse-env/install-hugrenv-action@main
      - uses: taiki-e/install-action@nextest
      - name: Test with all features
        run: cargo nextest r --verbose --all-features

  check-py:
    name: 🐍 Test Python code (${{ matrix.python-version }})
    needs: changes
    if: ${{ needs.changes.outputs.python == 'true' }}
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      LLVM_SYS_211_PREFIX: /usr/lib/llvm-21

    strategy:
      matrix:
        python-version: [ "3.13", "3.14" ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Install hugrenv
        uses: Quantinuum/hugrverse-env/install-hugrenv-action@main
        with:
          packages: llvm,tket
          lockfile: hugrenv.lock

      - name: Install dependencies
        run: uv sync --frozen --python ${{ env.PYTHON_VERSION }}

      - name: Run tests
        run: uv run pytest

  # Ensure that serialized extensions match rust implementation
  check-extensions:
    name: Check extensions
    needs: changes
    if: ${{ needs.changes.outputs.rust == 'true' && github.event_name != 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: mozilla-actions/sccache-action@v0.0.10
      - uses: quantinuum/hugrverse-env/install-hugrenv-action@main
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: extractions/setup-just@v4
      - name: Generate the updated definitions
        run: just gen-extensions
      - name: Check if the declarations are up to date
        run: |
          git diff --exit-code --name-only src/guppyft/extensions/data
          if [ $? -ne 0 ]; then
            echo "The serialized standard extensions are not up to date."
            echo "Please run 'just gen-extensions' and commit the changes.
            "
            exit 1
          fi
